### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by ahangarha** [i18n-l10n/calc#1]
Hi

I have been working on doing some how the same thing on several Free Software project. So I thought maybe it is good to share some of my thoughts.

What we need is to find a standard way to address bidi (bidirectional) text. So, the browser can intelligently decide the proper direction of text based on the context.

As soon as the direction is detected, text alignment can be set properly using start|end instead of left|right.

One of the workaround is to use `dir="auto"` to HTML tags like `p`. As the result, it detect the direction of paragraph based on the first character. This is being used by Gitlab as far as my understanding. I have used it on some projects like Plume and FluxBB and it works very well.

The other method is based on CSS and is by using `unicode-bidi: plaintext;`. I have used this recently for Sengi app and it works perfectly fine. But for many other projects, it doesn't and I couldn't figure it out why!

Finally, I suggest before inventing anything, do study the already existing approaches. I don't think we need a new framework. There should be a way to make all the existing ones support bidi.

I hope this project reaches somewhere good. This issue is really annoying.

All the best

**Comment by srfirouzi** [comment]
HI
Now, three class defined for direction
ltr,rtl,auto
ltr,rtl use for every layout and text 
auto use text like p tag

For define dynamic left and right, use "near" and "far" for every where, 
In rtl: near=right and far=left 
in ltr: near=left and far=right

**Comment by ahangarha** [comment]
Either I don't understand the project or closing this issue is not constructive.

Where can we discuss about the project? I have questions.
